### ISSUE TITLE
[FEAT] - URL da foto.

### ISSUE THREAD

**Issue by hdev14** [conab-devs/conab-backend#45]
<p align="center">
:pencil: Transformar o path da foto de usuário em url e returnar a url da foto após a efetuação do upload. :pencil:
</p>

## Links úteis :pushpin:
>Adicione alguns links úteis, como documentos, imagens, vídeos, etc.

**Comment by lucasemanuel8** [comment]
Hermin, tem o `Storage::url()`, vou usar para retornar o DAP.
