### ISSUE TITLE
[RF06] - Gerenciar Categorias de Produtos

### ISSUE THREAD

**Issue by FrankKleiton** [conab-devs/conab-backend#5]
<p align="center">
:pencil: Possibilitar o gerenciamento das categorias dos produtos por meio de operações de registro, atualização, visualização e exclusão dos dados. :pencil:
</p>

## Usuários Envolvidos :busts_in_silhouette:
Funcionário/Administrador da CONAB.

## Dependências :rotating_light:
- **RF17. Gerenciar Administradores da CONAB**

## Links úteis :pushpin:
> https://laravel.com/docs/7.x/authorization
> https://laravel.com/docs/7.x/eloquent
> https://laravel.com/docs/7.x/controllers#resource-controllers
> https://laravel.com/docs/7.x/eloquent-serialization
> https://laravel.com/docs/7.x/routing#route-model-binding

**Comment by hdev14** [comment]
#70
